"""
Healthcare Multi-Agent Pipeline — LangGraph
============================================
Supervisor routes deterministically through:
  triage -> diagnosis -> treatment -> report

No extra LLM calls in the supervisor — routing is pure Python logic,
making it fast, reliable, and free of routing errors.
"""

import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from typing import TypedDict, Literal
from langgraph.graph import StateGraph, END

from agents.triage    import run_triage
from agents.diagnosis import run_diagnosis
from agents.treatment import run_treatment


# ── State Schema ───────────────────────────────────────────────────────────────

class PatientState(TypedDict, total=False):
    # Patient inputs
    name:        str
    age:         int
    gender:      str
    symptoms:    str
    vitals:      str
    history:     str
    medications: str
    allergies:   str
    # Internal routing
    next_agent:       str
    completed_agents: list
    # Agent outputs
    triage_output:    str
    diagnosis_output: str
    treatment_output: str
    # Final
    final_report: str
    status:       str


# ── Supervisor (fully deterministic) ──────────────────────────────────────────

def supervisor_node(state: PatientState) -> PatientState:
    """
    Pure-Python routing — no LLM calls here.
    Checks completed_agents list and routes to the next required agent.
    """
    completed = state.get("completed_agents", [])

    if "triage" not in completed:
        next_agent = "triage"
    elif "diagnosis" not in completed:
        next_agent = "diagnosis"
    elif "treatment" not in completed:
        next_agent = "treatment"
    else:
        next_agent = "report"

    return {**state, "next_agent": next_agent, "status": f"Routing to: {next_agent}"}


def route_from_supervisor(
    state: PatientState,
) -> Literal["triage", "diagnosis", "treatment", "report"]:
    return state.get("next_agent", "triage")


# ── Agent Nodes ────────────────────────────────────────────────────────────────

def triage_node(state: PatientState) -> PatientState:
    result    = run_triage(dict(state))
    completed = list(state.get("completed_agents", []))
    if "triage" not in completed:
        completed.append("triage")
    return {**result, "completed_agents": completed, "status": "Triage complete"}


def diagnosis_node(state: PatientState) -> PatientState:
    result    = run_diagnosis(dict(state))
    completed = list(state.get("completed_agents", []))
    if "diagnosis" not in completed:
        completed.append("diagnosis")
    return {**result, "completed_agents": completed, "status": "Diagnosis complete"}


def treatment_node(state: PatientState) -> PatientState:
    result    = run_treatment(dict(state))
    completed = list(state.get("completed_agents", []))
    if "treatment" not in completed:
        completed.append("treatment")
    return {**result, "completed_agents": completed, "status": "Treatment complete"}


# ── Report Compiler ────────────────────────────────────────────────────────────

def report_node(state: PatientState) -> PatientState:
    report = f"""
================================================================
           HEALTHCARE AI CLINICAL REPORT
================================================================

PATIENT INFORMATION
-------------------
Name        : {state.get('name', 'Unknown')}
Age/Gender  : {state.get('age', '?')} / {state.get('gender', '?')}
Presenting  : {state.get('symptoms', 'N/A')}
Vitals      : {state.get('vitals', 'Not recorded')}
History     : {state.get('history', 'None reported')}
Medications : {state.get('medications', 'None')}
Allergies   : {state.get('allergies', 'NKDA')}

================================================================
 TRIAGE ASSESSMENT  [Agent 1/3]
================================================================
{state.get('triage_output', 'Not available')}

================================================================
 DIFFERENTIAL DIAGNOSIS  [Agent 2/3]
================================================================
{state.get('diagnosis_output', 'Not available')}

================================================================
 TREATMENT PLAN  [Agent 3/3]
================================================================
{state.get('treatment_output', 'Not available')}

================================================================
 DISCLAIMER
================================================================
This report is generated by an AI clinical decision support
system. All recommendations MUST be reviewed and approved by
a licensed healthcare professional before any clinical action.
This tool does not replace clinical judgment.

Pipeline : Supervisor -> Triage -> Diagnosis -> Treatment
Framework: LangGraph StateGraph
================================================================
"""
    completed = list(state.get("completed_agents", []))
    if "report" not in completed:
        completed.append("report")
    return {**state, "final_report": report, "completed_agents": completed, "status": "Report complete"}


# ── Build Graph ────────────────────────────────────────────────────────────────

def build_graph():
    g = StateGraph(PatientState)

    g.add_node("supervisor", supervisor_node)
    g.add_node("triage",     triage_node)
    g.add_node("diagnosis",  diagnosis_node)
    g.add_node("treatment",  treatment_node)
    g.add_node("report",     report_node)

    g.set_entry_point("supervisor")

    g.add_conditional_edges(
        "supervisor",
        route_from_supervisor,
        {"triage": "triage", "diagnosis": "diagnosis",
         "treatment": "treatment", "report": "report"},
    )

    g.add_edge("triage",    "supervisor")
    g.add_edge("diagnosis", "supervisor")
    g.add_edge("treatment", "supervisor")
    g.add_edge("report",    END)

    return g.compile()


# Compiled graph — module-level singleton
_graph = None

def _get_graph():
    global _graph
    if _graph is None:
        _graph = build_graph()
    return _graph


# ── Public API ─────────────────────────────────────────────────────────────────

def run_pipeline(patient_data: dict) -> dict:
    """Run the full multi-agent pipeline. Returns final state dict."""
    initial: PatientState = {
        "name":        patient_data.get("name",        "Unknown Patient"),
        "age":         patient_data.get("age",         0),
        "gender":      patient_data.get("gender",      "Unknown"),
        "symptoms":    patient_data.get("symptoms",    ""),
        "vitals":      patient_data.get("vitals",      "Not recorded"),
        "history":     patient_data.get("history",     "None"),
        "medications": patient_data.get("medications", "None"),
        "allergies":   patient_data.get("allergies",   "NKDA"),
        "completed_agents": [],
        "status": "Starting",
    }
    return _get_graph().invoke(initial)


if __name__ == "__main__":
    result = run_pipeline({
        "name": "Sarah Chen", "age": 45, "gender": "Female",
        "symptoms": "Severe headache, worst of her life, sudden onset. Visual changes, neck stiffness.",
        "vitals": "BP 180/115, HR 88, SpO2 98%",
        "history": "Hypertension, Migraines",
        "medications": "Amlodipine",
        "allergies": "Sulfa drugs",
    })
    print(result["final_report"])
